#!/bin/bash
# wemux by Matt Furden @zolrath
# version 1.3.1
#
# wemux allows you to start a shared tmux session using the command 'wemux'.
# Clients have the option of mirroring, which will give them read-only access,
# or pairing, which will allow them to edit your file (shared cursor) or work
# in another window (separate cursors) in the hosts tmux session.
#
# To set a user as host add their username to the host_list in /etc/wemux.conf
#
# For environments with multiple hosts running their own independent sessions
# on the same machine wemux can change its hostname with the wemux name command.
#
# WEMUX HOST COMMANDS:
# wemux start : Start the wemux session/join an existing wemux session.
# wemux attach: Join an existing wemux session.
# wemux stop  : Stop the wemux server, delete the socket.
# wemux help  : Display the help screen.
#
# WEMUX CLIENT COMMANDS:
# wemux mirror: Attach to Host in read-only mode.
# wemux pair  : Attach to Host in pair mode, which allows editing.
# wemux logout: Log out of the wemux pairing session.
# wemux help  : Display the help screen.
#
# WEMUX HOSTNAME COMMANDS: can be run by either host or client.
# wemux name  : Change hostname of wemux session.
# wemux reset : Reset host to default: host

###############################################################################

# Setup and Configuration Files.
# Default settings in case /etc/wemux.conf doesn't exist:
host_list=(root)
socket_prefix="/tmp/wemux"
options="-u"

# Load configuration options from /etc/wemux.conf
[ -f /etc/wemux.conf ] && . /etc/wemux.conf

# Load the hostname of last wemux session. If empty, set to host.
if [ -f ~/.wemux_last_host ]; then
  host=`cat ~/.wemux_last_host`
else
  host="host"
  echo $host > ~/.wemux_last_host
fi

# Set client's pair mode session name.
client_session="$host-$USER"
# Set socket to include hostname.
socket="${socket_prefix}-$host"
# Set $wemux to wemux session file.
wemux="tmux -S $socket $options"

# The ugly group of redirects below solve the issue where tmux/epoll causes tmux
# to hang when stderr is redirected to /dev/null in a backwards compatible way.

# Returns true if host currently has a running wemux server.
host_exists() {
  redirect=`$wemux has-session -t $host 2>&1`; does_exist=$?
  [ $does_exist == 0 ] && return 0 || return 1;
}

# Returns true if pair session with current host already exists.
has_pair_session() {
  redirect=`$wemux has-session -t $client_session 2>&1`; does_exist=$?
  [ $does_exist == 0 ] && return 0 || return 1;
}

# Returns true if server is successfully killed.
kill_server_successful() {
  redirect=`$wemux kill-server 2>&1`; killed_successfully=$?
  [ $killed_successfully == 0 ] && return 0 || return 1;
}

# Announce when user attaches/detaches from server.
# The first argument specifies the mode the user is attaching in for the message
# All additional arguments get wrapped in the attach/detach messages.
announce_connection() {
  connection_type=$1; shift; attach_commands="$@"
  redirect=`$wemux display-message "$USER has attached in $connection_type mode." 2>&1`
  $attach_commands
  redirect=`$wemux display-message "$USER has detached." 2>&1`
}

# Change hostname for session, or display hostname if no argument is given.
change_host() {
  if [ -z $1 ]; then
    echo "The current wemux host is set to $host"
  else
    echo "Changed wemux hostname from $host to $1"
    host="$1"
    echo $host > ~/.wemux_last_host
  fi
}

# Host mode, used when user is listed in the host_list array in /etc/wemux.conf
host_mode() {
  # Start the server if it doesn't exist, otherwise reattach.
  start_server() {
    if ! host_exists; then
      $wemux new-session -d -s $host
      chmod 1777 $socket
      echo "wemux server started on $host."
    fi
    reattach
  }

  # Reattach to the wemux session.
  reattach() {
    if host_exists; then
      $wemux attach -t $host
    else
      echo "No wemux session to attach to on $host."
    fi
  }

  # Stop the wemux session and remove the socket file.
  stop_server() {
    if kill_server_successful; then
      echo "wemux server on $host stopped."
    else
      echo "No wemux server running on $host."
    fi
    if [ -e $socket ]; then
      if rm $socket; then
        echo "Removed $socket."
      else
        echo "Could not remove $socket. Please check file ownership."
      fi
    else
      echo "The wemux socket $socket does not exist."
    fi
  }

  # Display the commands available in host mode.
  display_host_commands() {
    echo "The current wemux host is set to $host"
    echo "To host a wemux session please use one of the following:"
    echo ""
    echo "    [s]  start: Start the wemux session/join an existing wemux session."
    echo "    [a] attach: Join an existing wemux session."
    echo "    [k]   stop: Kill the wemux session, delete the socket."
    echo "    [n]   name: Set wemux hostname to supplied name."
    echo "    [r]  reset: Reset host to default: host"
    echo "    [h]   help: Display this screen."
    echo "       no args: Start the wemux session/join an existing wemux session."
  }

  # Host mode command handling:
  # If no command given, call start server.
  if [ -z "$1" ]; then
    start_server
  else
    case "$1" in
      start|s)  start_server;;
      attach|a) announce_connection host reattach;;
      join|j)   announce_connection host reattach;;
      stop|st)  stop_server;;
      kill|k)   stop_server;;
      name|n)   change_host $2;;
      help|h)   display_host_commands;;
      reset|r)  change_host host;;
      *)        if ! $wemux $1; then
                  display_host_commands
                fi;;
    esac
  fi
}

# Client Mode, used when user is NOT listed in the host_list in /etc/wemux.conf
client_mode() {
  # Mirror mode, allows the user to view wemux session in read only mode.
  mirror_mode() {
    if host_exists; then
      $wemux attach -t $host -r
    else
      echo "No wemux session to mirror on $host."
    fi
  }

  # Pair mode, allows user to interact with wemux session.
  # Will connect to existing pair session or create one if necessary.
  pair_mode() {
    if has_pair_session; then
      $wemux attach -t $client_session
    elif host_exists; then
      $wemux new-session -d -t $host -s $client_session
      $wemux new-window -n $USER
      $wemux attach -t $client_session
    else
      echo "No wemux session to pair with on $host."
    fi
  }

  # Log user out of pair mode, allows them to wemux pair HOSTNAME with another.
  logout_pair() {
    if has_pair_session; then
      $wemux display-message "$USER has logged out of pair mode."
      $wemux kill-session -t $client_session
      echo "Logged out of pair mode with $host."
    else
      echo "No wemux session to log out of with $host."
    fi
  }

  # Reattach based upon presence of existing pair mode session.
  # If pair mode session exists, reattach to it.
  # If no pair mode session exists, mirror the host.
  smart_reattach() {
    if has_pair_session; then
      announce_connection "pair" $wemux attach -t $client_session
    elif host_exists; then
      announce_connection "mirror" $wemux attach -t $host -r
    else
      echo "No wemux session to attach to on $host."
    fi
  }

  # Display the commands available in client mode.
  display_client_commands() {
    echo "The current wemux host is set to $host"
    echo "To connect to wemux please use one of the following:"
    echo ""
    echo "    [m] mirror: Attach to Host in read-only mode."
    echo "    [p]   pair: Attach to Host in pair mode, which allows editing."
    echo "    [l] logout: Log out of the current wemux pairing session."
    echo "    [n]   name: Set name of wemux hostname you wish to connect to."
    echo "    [r]  reset: Reset host to default: host"
    echo "    [h]   help: Display this screen."
    echo "       no args: Attach to pair session if it already exists, otherwise mirror."
  }

  # Client mode command handling:
  # If no command given, call smart_reattach
  if [ -z "$1" ]; then
    smart_reattach
  else
    case "$1" in
      mirror|m) announce_connection "mirror" mirror_mode;;
      pair|p)   announce_connection "pair" pair_mode;;
      edit|e)   announce_connection "pair" pair_mode;;
      logout|l) logout_pair;;
      stop|s)   logout_pair;;
      help|h)   display_client_commands;;
      name|n)   change_host $2;;
      reset|r)  change_host host;;
      *)        if ! $wemux $1; then
                  display_client_commands
                fi;;
    esac
  fi
}

# Check if current user is listed in the host_list.
user_is_a_host() {
  for user in "${host_list[@]}"; do
    [[ "$user" == "$USER" ]] && return 0
  done
  return 1
}

# Don't allow wemux to be run directly within a wemux session.
if [[ "$TMUX" != *$socket* ]]; then
  # If user is in host list, use host mode. If not, use client mode.
  if user_is_a_host; then
    host_mode "$@"
  else
    client_mode "$@"
  fi
else
  echo "You're already attached to the wemux session on $host"
  echo "wemux does not allow nesting wemux sessions directly."
fi
